### ISSUE TITLE
酷狗音源有问题

### ISSUE THREAD

**Issue by Finch-Origin** [ndroi/easy163#38]
java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to com.alibaba.fastjson.JSONArray
	at com.alibaba.fastjson.JSONObject.getJSONArray(JSONObject.java:123)
	at org.ndroi.easy163.providers.KugouMusic.collectCandidateKeywords(KugouMusic.java:42)
	at org.ndroi.easy163.core.Search$1.run(Search.java:38)
这是MIUI崩溃日志，虽然停止运行，但VPN服务还在，听部分歌曲时会弹出该报错，且歌曲只能听30s便会自动切换至下一首，就像是vip歌曲免费试听的感觉？
如果软件有自带日志的话倒是方便排错
软件版本1.7.5
歌曲：らびっとビビっとShow Time
麻烦了

**Comment by ndroi** [comment]
这首歌只有网易云有而且收费，修复了这个 bug 也听不了

**Comment by Finch-Origin** [comment]
这太惨了，算了，能修完不过也不错
