### ISSUE TITLE
终于有一个基于vpn的免root代理网易云了

### ISSUE THREAD

**Issue by myflavor** [ndroi/easy163#4]
手机红米K20Pro，安卓10，用这个APP没有效果，不知道为什么，周杰伦的歌还是灰色的

**Comment by myflavor** [comment]
网易云音乐版本7.2.10,
开了之后，状态栏没有VPN图标

**Comment by ndroi** [comment]
应该是 VPN 服务未启动成功，
这边安卓 10， 网易云同 7.2 版本，正常。
我这边无法获取你那边的日志，抱歉。

**Comment by myflavor** [comment]
我如何抓取日志

**Comment by myflavor** [comment]
我朋友的一加5 Android10也是这样

**Comment by ndroi** [comment]
打开服务后Home键后台 easy163，不要返回。
是这样操作的吗

**Comment by myflavor** [comment]
是这样操作的，后台是在的

**Comment by myflavor** [comment]
我会用Android studio的logcat，Java也会些，就是你这个项目导入好像要安装git，我安装了也没正常导入

**Comment by myflavor** [comment]
I/LocalVPNService: Started
I/Toast: Show toast from OpPackageName:org.ndroi.easy163, PackageName:org.ndroi.easy163

**Comment by myflavor** [comment]
有了有了，停止不了的日志，应该是没有正常启动导致的吧
D/stopVPN: try to stopVPN
W/System.err: java.lang.InterruptedException
W/System.err:     at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2042)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2076)
        at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:387)
        at org.ndroi.easy163.vpn.bio.BioTcpHandler.run(BioTcpHandler.java:555)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
W/System.err: java.lang.InterruptedException
W/System.err:     at java.lang.Thread.sleep(Native Method)
        at java.lang.Thread.sleep(Thread.java:440)
        at java.lang.Thread.sleep(Thread.java:356)
W/System.err:     at org.ndroi.easy163.vpn.LocalVPNService$VPNRunnable.run(LocalVPNService.java:272)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
E/BioUdpHandler: error
    java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2042)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2076)
        at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:387)
        at org.ndroi.easy163.vpn.bio.BioUdpHandler.run(BioUdpHandler.java:187)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
W/VPNRunnable: java.io.IOException: Bad file descriptor
    java.io.IOException: Bad file descriptor
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:53)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:197)
        at org.ndroi.easy163.vpn.LocalVPNService$VPNRunnable.run(LocalVPNService.java:249)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
I/LocalVPNService: Stopped
W/System.err: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2042)
W/System.err:     at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2076)
        at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:387)
        at org.ndroi.easy163.vpn.bio.BioTcpHandler.run(BioTcpHandler.java:555)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by ndroi** [comment]
不要点击停止，
把启动后的日志给我

**Comment by myflavor** [comment]
能加联系方式吗

**Comment by ndroi** [comment]
直接在这说吧

**Comment by myflavor** [comment]
尴尬了，我才发现只是VPN图标没有，logcat里面是有各种remote的，周杰伦的歌只能听前面50首吗？还是只能替换掉歌单里面的，实测歌单的变正常了

**Comment by ndroi** [comment]
只能前 50 首啥意思，你歌单里的前 50 首？

**Comment by myflavor** [comment]
未开启
![image](https://user-images.githubusercontent.com/45022747/89732399-4dda2600-da81-11ea-9660-5ed40ee635d8.png)
开启
![image](https://user-images.githubusercontent.com/45022747/89732408-56caf780-da81-11ea-97bd-00b682eb4b41.png)
开启（只有50首是正常的）
![image](https://user-images.githubusercontent.com/45022747/89732411-5d596f00-da81-11ea-98db-27e138eb7cc2.png)

**Comment by myflavor** [comment]
歌单刚好有两首周杰伦的，周杰伦前面48首+歌单的那两首就是50首了

**Comment by ndroi** [comment]
很奇怪，你退出去这个列表页面，重新点进来

**Comment by myflavor** [comment]
这是一直复现的

**Comment by ndroi** [comment]
感觉不太可能，你什么版本网易云

**Comment by myflavor** [comment]
V7.2.22.693056

**Comment by myflavor** [comment]
V7.2.10 安卓9也是这样

**Comment by ndroi** [comment]
你这明显是 easy163 挂掉了吧，
不可能一半正常一半灰色

**Comment by myflavor** [comment]
不可能，再回去我的歌单，还是正常的，而且logcat还有反应啊，也处理了那些请求了

**Comment by ndroi** [comment]
清空网易云缓存并关闭其进程再试试

**Comment by myflavor** [comment]
按照要求做了，但是仍然复发

**Comment by ndroi** [comment]
所有的歌单都这样吗，
是最新版本的 easy163 吗，
歌单前面正常，50 之后不行了？

**Comment by myflavor** [comment]
全部歌曲页面的问题
歌手页面
![image](https://user-images.githubusercontent.com/45022747/89733382-baf0ba00-da87-11ea-9509-871aa93e2c18.png)
歌手全部歌曲页面
![image](https://user-images.githubusercontent.com/45022747/89733387-c47a2200-da87-11ea-8dda-a79b64dfe606.png)

**Comment by myflavor** [comment]
只要点进全部歌曲，就没效果了

**Comment by ndroi** [comment]
OK，非常感谢，我已经复现了 bug 。
是因为代码未处理这里，
请暂时使用歌手专辑页播放

**Comment by myflavor** [comment]
好的

**Comment by myflavor** [comment]
顺便给大佬建议个界面，感觉软件空空的，输出一些日志，感觉就好多了
![image](https://user-images.githubusercontent.com/45022747/89734027-060ccc00-da8c-11ea-9c65-61817767e649.png)
![image](https://user-images.githubusercontent.com/45022747/89734037-18870580-da8c-11ea-90f3-c5697873dafb.png)

**Comment by ndroi** [comment]
好的好的

**Comment by ndroi** [comment]
我目前希望推广集赞，请多支持

**Comment by myflavor** [comment]
等大佬修复完这个bug，酷安发一发应该能火，因为现有的太极阴用unblock模块，会修改APP，导致一起听无法使用，虽然可以反编译将一起听异常的检测去掉，但是往微信分享一起听，会提示签名校验失败。

**Comment by ndroi** [comment]
感谢提交代码，功能已合并到最新版。
